# GET http://localhost:3001/api/persons

# DELETE http://localhost:3001/api/persons/1

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    
    "name": "JASON GREEN", 
    "number": "12-89-134357"
}

